### ISSUE TITLE
Can CodeBLEU be used to evaluate the similarity between codes in different languages? 

### ISSUE THREAD

**Issue by huhusmang** [k4black/codebleu#13]
Thank you very much for your implementation of the CodeBLEU evaluation method, it helped me a lot!
At the same time I have some questions:
1. Can CodeBLEU be used to evaluate the similarity between codes in different languages?
2. Is the evaluation of CodeBLEU at the corpus level like BLEU? If it is just to evaluate the CodeBLEU between two codes, is it accurate?

Looking forward to your reply! Thanks!

**Comment by k4black** [comment]
Hey,  
First of all, i am not an author of the original paper ["CodeBLEU: a Method for Automatic Evaluation of Code Synthesis"](https://arxiv.org/abs/2009.10297), so i can not speak for the metric officially, please refer to the paper.

1. As i know, no, it can not, because a) it relies on n-grams which will be different amount languages with different syntax b) uses tree-sitter which produce language-specific syntax trees

2.  It is a corpus metric because a) it has BLEU as it's components b) Uses dataflow match which requires corpus-dataflow to compute and for individual samples might be considered as "1"
